// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package schema

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonCef4e921DecodeGithubComDecafEmuHuehuetenangoPkgImporterSchema(in *jlexer.Lexer, out *RPL) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "exports":
			if in.IsNull() {
				in.Skip()
				out.Exports = nil
			} else {
				if out.Exports == nil {
					out.Exports = new(Exports)
				}
				(*out.Exports).UnmarshalEasyJSON(in)
			}
		case "imports":
			if in.IsNull() {
				in.Skip()
				out.Imports = nil
			} else {
				in.Delim('[')
				if out.Imports == nil {
					if !in.IsDelim(']') {
						out.Imports = make([]*Imports, 0, 8)
					} else {
						out.Imports = []*Imports{}
					}
				} else {
					out.Imports = (out.Imports)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *Imports
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(Imports)
						}
						(*v1).UnmarshalEasyJSON(in)
					}
					out.Imports = append(out.Imports, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "fileinfo":
			easyjsonCef4e921Decode(in, &out.FileInfo)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCef4e921EncodeGithubComDecafEmuHuehuetenangoPkgImporterSchema(out *jwriter.Writer, in RPL) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"exports\":")
	if in.Exports == nil {
		out.RawString("null")
	} else {
		(*in.Exports).MarshalEasyJSON(out)
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"imports\":")
	if in.Imports == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in.Imports {
			if v2 > 0 {
				out.RawByte(',')
			}
			if v3 == nil {
				out.RawString("null")
			} else {
				(*v3).MarshalEasyJSON(out)
			}
		}
		out.RawByte(']')
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"fileinfo\":")
	easyjsonCef4e921Encode(out, in.FileInfo)
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RPL) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCef4e921EncodeGithubComDecafEmuHuehuetenangoPkgImporterSchema(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RPL) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCef4e921EncodeGithubComDecafEmuHuehuetenangoPkgImporterSchema(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RPL) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCef4e921DecodeGithubComDecafEmuHuehuetenangoPkgImporterSchema(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RPL) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCef4e921DecodeGithubComDecafEmuHuehuetenangoPkgImporterSchema(l, v)
}
func easyjsonCef4e921Decode(in *jlexer.Lexer, out *struct {
	Filename string `json:"filename"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "filename":
			out.Filename = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCef4e921Encode(out *jwriter.Writer, in struct {
	Filename string `json:"filename"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"filename\":")
	out.String(string(in.Filename))
	out.RawByte('}')
}
func easyjsonCef4e921DecodeGithubComDecafEmuHuehuetenangoPkgImporterSchema1(in *jlexer.Lexer, out *Permission) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "Group":
			out.Group = TrimUint32(in.Uint32())
		case "Mask":
			out.Mask = HexUint64(in.Uint64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCef4e921EncodeGithubComDecafEmuHuehuetenangoPkgImporterSchema1(out *jwriter.Writer, in Permission) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Group\":")
	out.Uint32(uint32(in.Group))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Mask\":")
	out.Uint64(uint64(in.Mask))
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Permission) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCef4e921EncodeGithubComDecafEmuHuehuetenangoPkgImporterSchema1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Permission) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCef4e921EncodeGithubComDecafEmuHuehuetenangoPkgImporterSchema1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Permission) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCef4e921DecodeGithubComDecafEmuHuehuetenangoPkgImporterSchema1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Permission) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCef4e921DecodeGithubComDecafEmuHuehuetenangoPkgImporterSchema1(l, v)
}
func easyjsonCef4e921DecodeGithubComDecafEmuHuehuetenangoPkgImporterSchema2(in *jlexer.Lexer, out *Meta) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ProductCode":
			out.ProductCode = string(in.String())
		case "LongNameEnglish":
			out.LongNameEnglish = string(in.String())
		case "ShortNameEnglish":
			out.ShortNameEnglish = string(in.String())
		case "PublisherEnglish":
			out.PublisherEnglish = string(in.String())
		case "Region":
			out.Region = HexUint32(in.Uint32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCef4e921EncodeGithubComDecafEmuHuehuetenangoPkgImporterSchema2(out *jwriter.Writer, in Meta) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"ProductCode\":")
	out.String(string(in.ProductCode))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"LongNameEnglish\":")
	out.String(string(in.LongNameEnglish))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"ShortNameEnglish\":")
	out.String(string(in.ShortNameEnglish))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"PublisherEnglish\":")
	out.String(string(in.PublisherEnglish))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Region\":")
	out.Uint32(uint32(in.Region))
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Meta) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCef4e921EncodeGithubComDecafEmuHuehuetenangoPkgImporterSchema2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Meta) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCef4e921EncodeGithubComDecafEmuHuehuetenangoPkgImporterSchema2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Meta) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCef4e921DecodeGithubComDecafEmuHuehuetenangoPkgImporterSchema2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Meta) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCef4e921DecodeGithubComDecafEmuHuehuetenangoPkgImporterSchema2(l, v)
}
func easyjsonCef4e921DecodeGithubComDecafEmuHuehuetenangoPkgImporterSchema3(in *jlexer.Lexer, out *Imports) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]string, 0, 4)
					} else {
						out.Data = []string{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					v4 = string(in.String())
					out.Data = append(out.Data, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "functions":
			if in.IsNull() {
				in.Skip()
				out.Functions = nil
			} else {
				in.Delim('[')
				if out.Functions == nil {
					if !in.IsDelim(']') {
						out.Functions = make([]string, 0, 4)
					} else {
						out.Functions = []string{}
					}
				} else {
					out.Functions = (out.Functions)[:0]
				}
				for !in.IsDelim(']') {
					var v5 string
					v5 = string(in.String())
					out.Functions = append(out.Functions, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCef4e921EncodeGithubComDecafEmuHuehuetenangoPkgImporterSchema3(out *jwriter.Writer, in Imports) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"name\":")
	out.String(string(in.Name))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"data\":")
	if in.Data == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v6, v7 := range in.Data {
			if v6 > 0 {
				out.RawByte(',')
			}
			out.String(string(v7))
		}
		out.RawByte(']')
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"functions\":")
	if in.Functions == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v8, v9 := range in.Functions {
			if v8 > 0 {
				out.RawByte(',')
			}
			out.String(string(v9))
		}
		out.RawByte(']')
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Imports) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCef4e921EncodeGithubComDecafEmuHuehuetenangoPkgImporterSchema3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Imports) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCef4e921EncodeGithubComDecafEmuHuehuetenangoPkgImporterSchema3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Imports) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCef4e921DecodeGithubComDecafEmuHuehuetenangoPkgImporterSchema3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Imports) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCef4e921DecodeGithubComDecafEmuHuehuetenangoPkgImporterSchema3(l, v)
}
func easyjsonCef4e921DecodeGithubComDecafEmuHuehuetenangoPkgImporterSchema4(in *jlexer.Lexer, out *Exports) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "data":
			if in.IsNull() {
				in.Skip()
				out.Data = nil
			} else {
				in.Delim('[')
				if out.Data == nil {
					if !in.IsDelim(']') {
						out.Data = make([]string, 0, 4)
					} else {
						out.Data = []string{}
					}
				} else {
					out.Data = (out.Data)[:0]
				}
				for !in.IsDelim(']') {
					var v10 string
					v10 = string(in.String())
					out.Data = append(out.Data, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "functions":
			if in.IsNull() {
				in.Skip()
				out.Functions = nil
			} else {
				in.Delim('[')
				if out.Functions == nil {
					if !in.IsDelim(']') {
						out.Functions = make([]string, 0, 4)
					} else {
						out.Functions = []string{}
					}
				} else {
					out.Functions = (out.Functions)[:0]
				}
				for !in.IsDelim(']') {
					var v11 string
					v11 = string(in.String())
					out.Functions = append(out.Functions, v11)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCef4e921EncodeGithubComDecafEmuHuehuetenangoPkgImporterSchema4(out *jwriter.Writer, in Exports) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"data\":")
	if in.Data == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v12, v13 := range in.Data {
			if v12 > 0 {
				out.RawByte(',')
			}
			out.String(string(v13))
		}
		out.RawByte(']')
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"functions\":")
	if in.Functions == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v14, v15 := range in.Functions {
			if v14 > 0 {
				out.RawByte(',')
			}
			out.String(string(v15))
		}
		out.RawByte(']')
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Exports) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCef4e921EncodeGithubComDecafEmuHuehuetenangoPkgImporterSchema4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Exports) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCef4e921EncodeGithubComDecafEmuHuehuetenangoPkgImporterSchema4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Exports) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCef4e921DecodeGithubComDecafEmuHuehuetenangoPkgImporterSchema4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Exports) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCef4e921DecodeGithubComDecafEmuHuehuetenangoPkgImporterSchema4(l, v)
}
func easyjsonCef4e921DecodeGithubComDecafEmuHuehuetenangoPkgImporterSchema5(in *jlexer.Lexer, out *COS) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ArgString":
			out.ArgString = string(in.String())
		case "CodeGenerationSize":
			out.CodeGenerationSize = HexUint32(in.Uint32())
		case "CodeGenerationCore":
			out.CodeGenerationCore = HexUint32(in.Uint32())
		case "MaximumSize":
			out.MaximumSize = HexUint32(in.Uint32())
		case "MaximumCodeSize":
			out.MaximumCodeSize = HexUint32(in.Uint32())
		case "OverlayArena":
			out.OverlayArena = HexUint32(in.Uint32())
		case "Permission0":
			if in.IsNull() {
				in.Skip()
				out.Permission0 = nil
			} else {
				if out.Permission0 == nil {
					out.Permission0 = new(Permission)
				}
				(*out.Permission0).UnmarshalEasyJSON(in)
			}
		case "Permission1":
			if in.IsNull() {
				in.Skip()
				out.Permission1 = nil
			} else {
				if out.Permission1 == nil {
					out.Permission1 = new(Permission)
				}
				(*out.Permission1).UnmarshalEasyJSON(in)
			}
		case "Permission2":
			if in.IsNull() {
				in.Skip()
				out.Permission2 = nil
			} else {
				if out.Permission2 == nil {
					out.Permission2 = new(Permission)
				}
				(*out.Permission2).UnmarshalEasyJSON(in)
			}
		case "Permission3":
			if in.IsNull() {
				in.Skip()
				out.Permission3 = nil
			} else {
				if out.Permission3 == nil {
					out.Permission3 = new(Permission)
				}
				(*out.Permission3).UnmarshalEasyJSON(in)
			}
		case "Permission4":
			if in.IsNull() {
				in.Skip()
				out.Permission4 = nil
			} else {
				if out.Permission4 == nil {
					out.Permission4 = new(Permission)
				}
				(*out.Permission4).UnmarshalEasyJSON(in)
			}
		case "Permission5":
			if in.IsNull() {
				in.Skip()
				out.Permission5 = nil
			} else {
				if out.Permission5 == nil {
					out.Permission5 = new(Permission)
				}
				(*out.Permission5).UnmarshalEasyJSON(in)
			}
		case "Permission6":
			if in.IsNull() {
				in.Skip()
				out.Permission6 = nil
			} else {
				if out.Permission6 == nil {
					out.Permission6 = new(Permission)
				}
				(*out.Permission6).UnmarshalEasyJSON(in)
			}
		case "Permission7":
			if in.IsNull() {
				in.Skip()
				out.Permission7 = nil
			} else {
				if out.Permission7 == nil {
					out.Permission7 = new(Permission)
				}
				(*out.Permission7).UnmarshalEasyJSON(in)
			}
		case "Permission8":
			if in.IsNull() {
				in.Skip()
				out.Permission8 = nil
			} else {
				if out.Permission8 == nil {
					out.Permission8 = new(Permission)
				}
				(*out.Permission8).UnmarshalEasyJSON(in)
			}
		case "Permission9":
			if in.IsNull() {
				in.Skip()
				out.Permission9 = nil
			} else {
				if out.Permission9 == nil {
					out.Permission9 = new(Permission)
				}
				(*out.Permission9).UnmarshalEasyJSON(in)
			}
		case "Permission10":
			if in.IsNull() {
				in.Skip()
				out.Permission10 = nil
			} else {
				if out.Permission10 == nil {
					out.Permission10 = new(Permission)
				}
				(*out.Permission10).UnmarshalEasyJSON(in)
			}
		case "Permission11":
			if in.IsNull() {
				in.Skip()
				out.Permission11 = nil
			} else {
				if out.Permission11 == nil {
					out.Permission11 = new(Permission)
				}
				(*out.Permission11).UnmarshalEasyJSON(in)
			}
		case "Permission12":
			if in.IsNull() {
				in.Skip()
				out.Permission12 = nil
			} else {
				if out.Permission12 == nil {
					out.Permission12 = new(Permission)
				}
				(*out.Permission12).UnmarshalEasyJSON(in)
			}
		case "Permission13":
			if in.IsNull() {
				in.Skip()
				out.Permission13 = nil
			} else {
				if out.Permission13 == nil {
					out.Permission13 = new(Permission)
				}
				(*out.Permission13).UnmarshalEasyJSON(in)
			}
		case "Permission14":
			if in.IsNull() {
				in.Skip()
				out.Permission14 = nil
			} else {
				if out.Permission14 == nil {
					out.Permission14 = new(Permission)
				}
				(*out.Permission14).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCef4e921EncodeGithubComDecafEmuHuehuetenangoPkgImporterSchema5(out *jwriter.Writer, in COS) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"ArgString\":")
	out.String(string(in.ArgString))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"CodeGenerationSize\":")
	out.Uint32(uint32(in.CodeGenerationSize))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"CodeGenerationCore\":")
	out.Uint32(uint32(in.CodeGenerationCore))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"MaximumSize\":")
	out.Uint32(uint32(in.MaximumSize))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"MaximumCodeSize\":")
	out.Uint32(uint32(in.MaximumCodeSize))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"OverlayArena\":")
	out.Uint32(uint32(in.OverlayArena))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Permission0\":")
	if in.Permission0 == nil {
		out.RawString("null")
	} else {
		(*in.Permission0).MarshalEasyJSON(out)
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Permission1\":")
	if in.Permission1 == nil {
		out.RawString("null")
	} else {
		(*in.Permission1).MarshalEasyJSON(out)
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Permission2\":")
	if in.Permission2 == nil {
		out.RawString("null")
	} else {
		(*in.Permission2).MarshalEasyJSON(out)
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Permission3\":")
	if in.Permission3 == nil {
		out.RawString("null")
	} else {
		(*in.Permission3).MarshalEasyJSON(out)
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Permission4\":")
	if in.Permission4 == nil {
		out.RawString("null")
	} else {
		(*in.Permission4).MarshalEasyJSON(out)
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Permission5\":")
	if in.Permission5 == nil {
		out.RawString("null")
	} else {
		(*in.Permission5).MarshalEasyJSON(out)
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Permission6\":")
	if in.Permission6 == nil {
		out.RawString("null")
	} else {
		(*in.Permission6).MarshalEasyJSON(out)
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Permission7\":")
	if in.Permission7 == nil {
		out.RawString("null")
	} else {
		(*in.Permission7).MarshalEasyJSON(out)
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Permission8\":")
	if in.Permission8 == nil {
		out.RawString("null")
	} else {
		(*in.Permission8).MarshalEasyJSON(out)
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Permission9\":")
	if in.Permission9 == nil {
		out.RawString("null")
	} else {
		(*in.Permission9).MarshalEasyJSON(out)
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Permission10\":")
	if in.Permission10 == nil {
		out.RawString("null")
	} else {
		(*in.Permission10).MarshalEasyJSON(out)
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Permission11\":")
	if in.Permission11 == nil {
		out.RawString("null")
	} else {
		(*in.Permission11).MarshalEasyJSON(out)
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Permission12\":")
	if in.Permission12 == nil {
		out.RawString("null")
	} else {
		(*in.Permission12).MarshalEasyJSON(out)
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Permission13\":")
	if in.Permission13 == nil {
		out.RawString("null")
	} else {
		(*in.Permission13).MarshalEasyJSON(out)
	}
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"Permission14\":")
	if in.Permission14 == nil {
		out.RawString("null")
	} else {
		(*in.Permission14).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v COS) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCef4e921EncodeGithubComDecafEmuHuehuetenangoPkgImporterSchema5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v COS) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCef4e921EncodeGithubComDecafEmuHuehuetenangoPkgImporterSchema5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *COS) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCef4e921DecodeGithubComDecafEmuHuehuetenangoPkgImporterSchema5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *COS) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCef4e921DecodeGithubComDecafEmuHuehuetenangoPkgImporterSchema5(l, v)
}
func easyjsonCef4e921DecodeGithubComDecafEmuHuehuetenangoPkgImporterSchema6(in *jlexer.Lexer, out *App) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "TitleID":
			out.TitleID = HexUint64(in.Uint64())
		case "TitleVersion":
			out.TitleVersion = HexUint16(in.Uint16())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonCef4e921EncodeGithubComDecafEmuHuehuetenangoPkgImporterSchema6(out *jwriter.Writer, in App) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"TitleID\":")
	out.Uint64(uint64(in.TitleID))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"TitleVersion\":")
	out.Uint16(uint16(in.TitleVersion))
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v App) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonCef4e921EncodeGithubComDecafEmuHuehuetenangoPkgImporterSchema6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v App) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonCef4e921EncodeGithubComDecafEmuHuehuetenangoPkgImporterSchema6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *App) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonCef4e921DecodeGithubComDecafEmuHuehuetenangoPkgImporterSchema6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *App) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonCef4e921DecodeGithubComDecafEmuHuehuetenangoPkgImporterSchema6(l, v)
}
