language: go
go:
  - master

before_install:
  - . $HOME/.nvm/nvm.sh
  - cd static && nvm install && nvm use && cd ..
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - make
