language: go
go:
  - master

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - curl -o- -L https://yarnpkg.com/install.sh | bash

install:
  - npm rebuild

script:
  - make
